/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacaobodega;

import Classes.Bodega;
import Classes.EstoqueArrayList;
import Classes.Produto;
import Classes.ProdutoPerecivel;
import Excecoes.PNEException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class EstoqueView extends javax.swing.JFrame {

    EstoqueArrayList estoque = new EstoqueArrayList();
    Bodega bodega = new Bodega(estoque);
    ArrayList<Produto> listaProdutos = new ArrayList();
    IncluirProdutoView recebeInstancia;
    
    private boolean venda = true;
    
    
    public EstoqueView() {
        initComponents();
        carregarEstoque();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        btEstocar = new javax.swing.JButton();
        btVender = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btAdicionar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btProdutosEmFalta = new javax.swing.JButton();
        jtQnt = new javax.swing.JTextField();
        jbConfirmar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnSobre = new javax.swing.JMenu();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estoque");

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome do Produto", "Preço (Em R$)", "Em Estoque", "Validade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbProdutos);
        if (tbProdutos.getColumnModel().getColumnCount() > 0) {
            tbProdutos.getColumnModel().getColumn(0).setResizable(false);
            tbProdutos.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbProdutos.getColumnModel().getColumn(1).setResizable(false);
            tbProdutos.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbProdutos.getColumnModel().getColumn(2).setResizable(false);
            tbProdutos.getColumnModel().getColumn(2).setPreferredWidth(5);
            tbProdutos.getColumnModel().getColumn(3).setResizable(false);
            tbProdutos.getColumnModel().getColumn(3).setPreferredWidth(5);
            tbProdutos.getColumnModel().getColumn(4).setResizable(false);
            tbProdutos.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        btEstocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacaobodega/Create.png"))); // NOI18N
        btEstocar.setText("Estocar");
        btEstocar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEstocarMouseClicked(evt);
            }
        });

        btVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacaobodega/Euro.png"))); // NOI18N
        btVender.setText("Vender");
        btVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVenderMouseClicked(evt);
            }
        });

        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacaobodega/Delete.png"))); // NOI18N
        btRemover.setText("Remover");
        btRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemoverMouseClicked(evt);
            }
        });

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacaobodega/Add.png"))); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAdicionarMouseClicked(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacaobodega/Redo.png"))); // NOI18N
        btAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAtualizarMouseClicked(evt);
            }
        });

        btProdutosEmFalta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacaobodega/3d bar chart.png"))); // NOI18N
        btProdutosEmFalta.setText(" Produtos em Falta");
        btProdutosEmFalta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProdutosEmFaltaMouseClicked(evt);
            }
        });

        jtQnt.setEnabled(false);

        jbConfirmar.setText("Ok");
        jbConfirmar.setEnabled(false);
        jbConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbConfirmarMouseClicked(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btEstocar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVender, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btProdutosEmFalta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btProdutosEmFalta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVender)
                        .addComponent(btEstocar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfirmar)
                    .addComponent(jbCancelar))
                .addGap(20, 20, 20))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAdicionar, btEstocar, btRemover, btVender});

        mnSobre.setText("Sobre");
        mnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSobreMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnSobre);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtualizarMouseClicked
        this.carregarEstoque();
    }//GEN-LAST:event_btAtualizarMouseClicked

    private void btProdutosEmFaltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProdutosEmFaltaMouseClicked
        this.carregarProdutosEmFalta();
    }//GEN-LAST:event_btProdutosEmFaltaMouseClicked

    private void mnSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSobreMouseClicked
        JOptionPane.showMessageDialog(this, "Trabalho Final de Técnicas de Programação por Isaac Müller \n"
                + "estudante de Ciência da Computação na UFC", "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnSobreMouseClicked

    private void btAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAdicionarMouseClicked
        if(recebeInstancia == null){
            recebeInstancia = new IncluirProdutoView(EstoqueView.this);
            recebeInstancia.setVisible(true);
            recebeInstancia.recebeEstoque(bodega);
        }else{
            recebeInstancia.setVisible(true);
            recebeInstancia.recebeEstoque(bodega);
        }
    }//GEN-LAST:event_btAdicionarMouseClicked

    private void btRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoverMouseClicked
        int row = tbProdutos.getSelectedRow();
        String cod = (String) tbProdutos.getValueAt(row, 0);
        try{
            bodega.removerProduto(cod);
        }catch(PNEException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        
        carregarEstoque();
    }//GEN-LAST:event_btRemoverMouseClicked

    private void btEstocarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEstocarMouseClicked
        prepararVendaEstoca(false);
    }//GEN-LAST:event_btEstocarMouseClicked

    private void jbCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelarMouseClicked
        Cancela();
    }//GEN-LAST:event_jbCancelarMouseClicked

    private void btVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVenderMouseClicked
        prepararVendaEstoca(true);
    }//GEN-LAST:event_btVenderMouseClicked

    private void jbConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbConfirmarMouseClicked
        int row = tbProdutos.getSelectedRow();
        String cod = (String) tbProdutos.getValueAt(row, 0);
        int qnt = Integer.parseInt(jtQnt.getText());
        try{
            if(venda){
                bodega.venderProduto(cod, qnt);
            }else{
                bodega.estocarProduto(cod, qnt);
            }
        }catch(PNEException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro",  JOptionPane.ERROR_MESSAGE);
        }
        carregarEstoque();
        Cancela();
    }//GEN-LAST:event_jbConfirmarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueView().setVisible(true);
            }
        });
        
        
    }
    
    public void carregarEstoque(){
        listaProdutos = estoque.produtosEmEstoque();
        
        DefaultTableModel modelo = (DefaultTableModel)tbProdutos.getModel(); 
        modelo.setNumRows(0);
        int cont = listaProdutos.size();
        for(int i = 0; i<cont; i++){
            if(listaProdutos.get(i) instanceof ProdutoPerecivel){
                ProdutoPerecivel p = (ProdutoPerecivel)listaProdutos.get(i);
                modelo.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNome(),
                    p.getPreco(),
                    p.getQuantidade(),
                    p.getValidade()
                });
            }else{
                modelo.addRow(new Object[]{
                    listaProdutos.get(i).getCodigo(),
                    listaProdutos.get(i).getNome(),
                    listaProdutos.get(i).getPreco(),
                    listaProdutos.get(i).getQuantidade(),
                });
            }
            
        }
    }
    public void carregarProdutosEmFalta(){
        listaProdutos = estoque.produtosEmFalta();
        
        DefaultTableModel modelo = (DefaultTableModel)tbProdutos.getModel(); 
        modelo.setNumRows(0);
        int cont = listaProdutos.size();
        for(int i = 0; i<cont; i++){
            if(listaProdutos.get(i) instanceof ProdutoPerecivel){
                ProdutoPerecivel p = (ProdutoPerecivel) listaProdutos.get(i);
                
                modelo.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNome(),
                    p.getPreco(),
                    p.getQuantidade(), 
                 p.getValidade(),
                });
            }else{
                modelo.addRow(new Object[]{
                    listaProdutos.get(i).getCodigo(),
                    listaProdutos.get(i).getNome(),
                    listaProdutos.get(i).getPreco(),
                    listaProdutos.get(i).getQuantidade(),
                });
            }
        }
    }
    
    public void prepararVendaEstoca(boolean op){
        btAdicionar.setEnabled(false);
        btAtualizar.setEnabled(false);
        btProdutosEmFalta.setEnabled(false);
        btRemover.setEnabled(false);
        jtQnt.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbConfirmar.setEnabled(true);
        jtQnt.requestFocus(true);
        this.venda = op;
    }
    
    public void Cancela(){
        btAdicionar.setEnabled(true);
        btAtualizar.setEnabled(true);
        btProdutosEmFalta.setEnabled(true);
        btRemover.setEnabled(true);
        jtQnt.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbConfirmar.setEnabled(false);
        jtQnt.requestFocus(false);
        jtQnt.setText("");
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAdicionar;
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btEstocar;
    public javax.swing.JButton btProdutosEmFalta;
    public javax.swing.JButton btRemover;
    public javax.swing.JButton btVender;
    public javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTree jTree1;
    public javax.swing.JButton jbCancelar;
    public javax.swing.JButton jbConfirmar;
    public javax.swing.JTextField jtQnt;
    public javax.swing.JMenu mnSobre;
    public javax.swing.JTable tbProdutos;
    // End of variables declaration//GEN-END:variables
}
